### ISSUE TITLE
Necessari gli xml

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#10]
Sono necessari gli xml latiposti, longiposti, nomiposti?

**Comment by GiovanniRoso** [comment]
No Professore, sono rimanenze di tentativi precedenti per l'ottenimento della lista dei luoghi visitabili. Ora quindi superflui.

**Comment by PorfirioTramontana** [comment]
Prova a toglierli e vedere se tutto funziona.

**Comment by GiovanniRoso** [comment]
Eliminati, funziona tutto.
