### ISSUE TITLE
Unificazione dati web/app

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#11]
Applicazione web e app prendono i dati da due fonti diverse, in due formati diversi.

Provate ad uniformarli, in modo che prendano dati dalla stessa fonte (va bene anche se mettete due copie dello stesso file sul server node.js e su uno spazio altervista).

**Comment by Hikarifede** [comment]
Risolto, adesso anche l'app web prende i dati dallo stesso spazio altervista e non più tramite file.json

**Comment by PorfirioTramontana** [comment]
OK: funziona bene!
