### ISSUE TITLE
Text in MainActivity

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#2]
In MainActivity mi risulta un testo "TextView"

**Comment by PorfirioTramontana** [comment]
Probabile problema di asincronia: il testo è scritto prima di effettuare il login

**Comment by GiovanniRoso** [comment]
Professore lì nome compare a seguito del login, non andando a buon fine il login rimane il testo di default.

**Comment by PorfirioTramontana** [comment]
Ho capito; il problema da gestire, allora, è che o gestite la possibilità di navigare l'app senza login oppure, quando il login va male, l'app dovrebbe chiudersi

**Comment by GiovanniRoso** [comment]
Non dovrebbe essere un problema. Proviamo a risolvere quanto prima.
