### ISSUE TITLE
Click su Preferiti

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#5]
Il click su di un preferito della lista dovrebbe riportare alla Activity con la mappa che sia centrata sul preferito prescelto.

**Comment by GiovanniRoso** [comment]
Questo è molto difficile, dovremmo salvare nel database anche le coordinate per poi portare l'utente alla acitivity con le indicazioni. Ci proveremo comunque.

**Comment by PorfirioTramontana** [comment]
potete chiamare l'attività delle mappe passando latitudine e longitudine tramite l'intent

**Comment by GiovanniRoso** [comment]
I preferiti vengono visualizzati grazie ad un collegamento al database firebase, in cui salviamo solo il nome del luogo che viene salvato dall'utente come preferito.
Ciò che Lei dice lo facciamo già dalla activity Download (che va a prendersi i dati da altervista) e tramite intent li passa alla activity con le indicazioni.
Per il momento ho messo un mezzo rattoppo, cliccando sul preferito si viene reindirizzati alla activity Maps però con latitudine e longitudine finti, in questo modo l'utente può quantomeno eliminare più velocemente il luogo dai preferiti. 
Credo che il salvataggio nel database firebase di latitudine e longitudine dovrebbe portare alla risoluzione del problema.

**Comment by GiovanniRoso** [comment]
Risolto. Funziona.
