### ISSUE TITLE
Perchè avete messo il Timer?

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#6]
Era necessario?

**Comment by Hikarifede** [comment]
Abbiamo messo il timer sia nella versione mobile che web per simulare una schermata di caricamento, quindi per un fine puramente estetico.

**Comment by PorfirioTramontana** [comment]
Vabbè, non lo avrei immaginato ci fosse gusto nel rallentare le applicazioni!
