### ISSUE TITLE
Codice necessario?

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#7]
A cosa serve questa parte di codice? E' necessaria?

btnToSecondAct.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (userEmailString.equals("rosoliagiovanni@gmail.com")) {
                    i.putExtra("userEmail", userEmailString);
                    i.putExtra("userName", name);
                    startActivity(i);
                }
                if (!userEmailString.equals("rosoliagiovanni@gmail.com")){
                    i2.putExtra("userEmail", userEmailString);
                    i2.putExtra("userName", name);
                    startActivity(i2);

                }

**Comment by Hikarifede** [comment]
Non è necessario, si trattava di un test per vedere se, accedendo come amministratore, fosse possibile effettuare azioni diverse da un utente qualsiasi.

**Comment by PorfirioTramontana** [comment]
Pure qua, prova a togliere e vedere se tutto funziona ancora

**Comment by GiovanniRoso** [comment]
abbiamo riutilizzato questo codice per fare un controllo sul nome e sulla mail in modo da far chiudere l'app se risulta qualche anomalia.
