### ISSUE TITLE
Citta' e attivita' bloccate

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#8]
Sia l'elenco delle città che quello delle possibili attività sono cablate (bloccate) all'interno del codice dell'applicazione, cosicchè non è possibile aggiungerne altre.

Sarebbe stato meglio, invece, aggiungere anche questi due campi nel file (html) che andate a consultare.

**Comment by GiovanniRoso** [comment]
Sia le città che il tipo di luogo da visitare sono ora ottenuti da altervista.
