### ISSUE TITLE
Applicazione monolingua

### ISSUE THREAD

**Issue by PorfirioTramontana** [GiovanniRoso/CulTrip#9]
In particolare, per come sono scritte le stringhe nel codice, bisogna ripensarla abbastanza per renderla multilingua.

**Comment by GiovanniRoso** [comment]
Fatto. Professore.... buonanotte

**Comment by PorfirioTramontana** [comment]
Si potrebbe forse risolvere il problema dei testi non modificabili scrivendo una risorsa per la stringa "tipodiposto" e un altro file tradotto (anche nel nome .html sul server altervista

**Comment by GiovanniRoso** [comment]
![Cattura](https://user-images.githubusercontent.com/50442190/59114682-feadd800-8947-11e9-82eb-fa0031a83bc1.PNG)
Andata anche questa!
